[package]
name = "osmquadtree"
version = "0.1.0"
authors = ["James Harris <jimbo.harris@gmail.com>"]
edition = "2018"

[dependencies]
#flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
flate2 = { version = "1.0", features = ["zlib"] }
#flate2 = { version = "1.0.17", features = ["zlib-ng-compat"],  default-features = false }
cpuprofiler = "0.0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
#crossbeam = "0.7"
#bitvec = "0.19"
chrono = "0.4.0"
cpu-time="1.0.0"
quick-xml="0.20"
csv = "1.1"
indicatif = "0.15"
[profile.release]
#debug = true

