pub const _DEFAULT_MINAREA_VALUES: &str = r#"
natural,water,4
landuse,reservoir,4
waterway,riverbank,4
natural,strait,3000
landuse,basin,3000
natural,bay,3000
waterway,dock,3000
"#;

pub const DEFAULT_MINZOOM_VALUES: &str = r#"
type,key,val,minzoom,table
0,addr:housename,*,17,point
0,addr:housenumber,*,17,point
0,aerialway,station,13,point
0,aeroway,aerodrome,10,point
0,aeroway,apron,17,point
0,aeroway,gate,17,point
0,aeroway,helipad,16,point
0,amenity,atm,17,point
0,amenity,bank,17,point
0,amenity,bar,17,point
0,amenity,bench,19,point
0,amenity,bicycle_parking,17,point
0,amenity,bicycle_rental,17,point
0,amenity,biergarten,17,point
0,amenity,bureau_de_change,18,point
0,amenity,bus_station,16,point
0,amenity,cafe,17,point
0,amenity,care_home,18,point
0,amenity,car_rental,17,point
0,amenity,car_sharing,18,point
0,amenity,car_wash,17,point
0,amenity,charging_station,18,point
0,amenity,church_hall,18,point
0,amenity,cinema,16,point
0,amenity,clinic,16,point
0,amenity,clock,18,point
0,amenity,college,17,point
0,amenity,community_centre,17,point
0,amenity,community_hall,18,point
0,amenity,courthouse,16,point
0,amenity,dentist,17,point
0,amenity,doctors,17,point
0,amenity,dog_bin,18,point
0,amenity,drinking_water,17,point
0,amenity,embassy,17,point
0,amenity,emergency_phone,17,point
0,amenity,fast_food,17,point
0,amenity,ferry_terminal,18,point
0,amenity,fire_station,16,point
0,amenity,food_court,17,point
0,amenity,fountain,17,point
0,amenity,fuel,17,point
0,amenity,grave_yard,17,point
0,amenity,grit_bin,18,point
0,amenity,hall,18,point
0,amenity,health_centre,18,point
0,amenity,hospital,15,point
0,amenity,hunting_stand,16,point
0,amenity,ice_cream,17,point
0,amenity,kindergarten,17,point
0,amenity,library,16,point
0,amenity,litter_bin,18,point
0,amenity,marketplace,18,point
0,amenity,motorcycle_parking,17,point
0,amenity,nightclub,17,point
0,amenity,notice_board,18,point
0,amenity,nursing_home,18,point
0,amenity,parking,17,point
0,amenity,parking_entrance,18,point
0,amenity,pharmacy,17,point
0,amenity,place_of_worship,16,point
0,amenity,police,16,point
0,amenity,post_box,17,point
0,amenity,post_office,17,point
0,amenity,prison,17,point
0,amenity,pub,17,point
0,amenity,public_building,18,point
0,amenity,recycling,17,point
0,amenity,restaurant,17,point
0,amenity,school,17,point
0,amenity,shelter,16,point
0,amenity,social_club,18,point
0,amenity,social_facility,17,point
0,amenity,swimming_pool,18,point
0,amenity,taxi,17,point
0,amenity,telephone,17,point
0,amenity,theatre,16,point
0,amenity,toilets,17,point
0,amenity,townhall,16,point
0,amenity,trolley_bay,18,point
0,amenity,university,17,point
0,amenity,vending_machine,18,point
0,amenity,veterinary,17,point
0,amenity,waste_basket,19,point
0,barrier,block,16,point
0,barrier,bollard,16,point
0,barrier,chicane,18,point
0,barrier,cycle_barrier,18,point
0,barrier,entrance,18,point
0,barrier,fence,18,point
0,barrier,gate,16,point
0,barrier,kissing_gate,18,point
0,barrier,lift_gate,16,point
0,barrier,stile,18,point
0,barrier,swing_gate,16,point
0,barrier,yes,18,point
0,boundary,national_park,17,point
0,highway,bus_stop,16,point
0,highway,crossing,18,point
0,highway,elevator,18,point
0,highway,ford,16,point
0,highway,give_way,18,point
0,highway,milestone,18,point
0,highway,mini_roundabout,16,point
0,highway,motorway_junction,11,point
0,highway,rest_area,17,point
0,highway,services,17,point
0,highway,speed_camera,18,point
0,highway,steps,18,point
0,highway,stop,18,point
0,highway,street_lamp,18,point
0,highway,traffic_signals,14,point
0,highway,turning_circle,15,point
0,highway,turning_loop,15,point
0,historic,archaeological_site,16,point
0,historic,memorial,17,point
0,historic,monument,16,point
0,historic,ruins,18,point
0,historic,wayside_cross,16,point
0,junction,yes,14,point
0,landuse,allotments,17,point
0,landuse,basin,17,point
0,landuse,brownfield,17,point
0,landuse,cemetery,17,point
0,landuse,commercial,17,point
0,landuse,construction,17,point
0,landuse,farm,17,point
0,landuse,farmland,17,point
0,landuse,farmyard,17,point
0,landuse,forest,17,point
0,landuse,garages,12,point
0,landuse,grass,17,point
0,landuse,greenhouse_horticulture,17,point
0,landuse,industrial,17,point
0,landuse,landfill,17,point
0,landuse,meadow,17,point
0,landuse,military,17,point
0,landuse,orchard,17,point
0,landuse,quarry,17,point
0,landuse,railway,17,point
0,landuse,recreation_ground,17,point
0,landuse,reservoir,17,point
0,landuse,residential,17,point
0,landuse,retail,17,point
0,landuse,village_green,17,point
0,landuse,vineyard,17,point
0,leisure,common,17,point
0,leisure,fitness_centre,18,point
0,leisure,fitness_station,18,point
0,leisure,garden,17,point
0,leisure,golf_course,15,point
0,leisure,marina,15,point
0,leisure,miniature_golf,17,point
0,leisure,nature_reserve,17,point
0,leisure,park,17,point
0,leisure,picnic_table,17,point
0,leisure,pitch,17,point
0,leisure,playground,14,point
0,leisure,recreation_ground,17,point
0,leisure,slipway,17,point
0,leisure,sports_centre,17,point
0,leisure,stadium,17,point
0,leisure,swimming_pool,14,point
0,leisure,track,17,point
0,leisure,water_park,14,point
0,man_made,chimney,18,point
0,man_made,cross,16,point
0,man_made,flagpole,18,point
0,man_made,lighthouse,15,point
0,man_made,mast,17,point
0,man_made,petroleum_well,18,point
0,man_made,silo,18,point
0,man_made,surveillance,18,point
0,man_made,survey_point,18,point
0,man_made,tower,18,point
0,man_made,water_tower,17,point
0,man_made,windmill,16,point
0,military,bunker,18,point
0,military,danger_area,17,point
0,natural,bare_rock,17,point
0,natural,bay,14,point
0,natural,beach,17,point
0,natural,cave_entrance,15,point
0,natural,glacier,17,point
0,natural,grassland,17,point
0,natural,heath,17,point
0,natural,marsh,17,point
0,natural,mud,17,point
0,natural,peak,11,point
0,natural,reef,17,point
0,natural,saddle,15,point
0,natural,sand,17,point
0,natural,scree,17,point
0,natural,scrub,17,point
0,natural,shingle,17,point
0,natural,shoal,17,point
0,natural,spring,14,point
0,natural,tree,16,point
0,natural,tree_row,16,point
0,natural,volcano,11,point
0,natural,water,17,point
0,natural,wetland,17,point
0,natural,wood,17,point
0,place,city,4,point
0,place,farm,15,point
0,place,hamlet,15,point
0,place,island,6,point
0,place,islet,14,point
0,place,isolated_dwelling,15,point
0,place,locality,15,point
0,place,neighbourhood,15,point
0,place,suburb,12,point
0,place,town,6,point
0,place,village,12,point
0,power,generator,15,point
0,power,plant,17,point
0,power,pole,16,point
0,power,station,17,point
0,power,sub_station,17,point
0,power,substation,17,point
0,power,switch,18,point
0,power,tower,14,point
0,power,transformer,18,point
0,railway,buffer_stop,18,point
0,railway,crossing,15,point
0,railway,halt,13,point
0,railway,level_crossing,14,point
0,railway,station,12,point
0,railway,stop,18,point
0,railway,subway_entrance,18,point
0,railway,switch,18,point
0,railway,tram_stop,13,point
0,shop,*,17,point
0,shop,department_store,16,point
0,shop,supermarket,16,point
0,tourism,alpine_hut,13,point
0,tourism,artwork,18,point
0,tourism,attraction,17,point
0,tourism,camp_site,16,point
0,tourism,caravan_site,16,point
0,tourism,chalet,17,point
0,tourism,guest_house,17,point
0,tourism,hostel,17,point
0,tourism,hotel,17,point
0,tourism,information,17,point
0,tourism,motel,17,point
0,tourism,museum,16,point
0,tourism,picnic_site,16,point
0,tourism,theme_park,17,point
0,tourism,viewpoint,16,point
0,tourism,zoo,17,point
0,waterway,dam,17,point
0,waterway,lock_gate,17,point
0,waterway,weir,17,point
1,addr:interpolation,*,17,line
1,aerialway,cable_car,12,highway
1,aerialway,chair_lift,12,highway
1,aerialway,drag_lift,12,highway
1,aerialway,gondola,12,highway
1,aerialway,goods,12,highway
1,aerialway,j-bar,12,highway
1,aerialway,platter,12,highway
1,aerialway,rope_tow,12,highway
1,aerialway,t-bar,12,highway
1,aeroway,runway,11,highway
1,aeroway,taxiway,11,highway
1,barrier,bollard,18,line
1,barrier,chain,16,line
1,barrier,city_wall,16,line
1,barrier,ditch,16,line
1,barrier,embankment,14,line
1,barrier,fence,16,line
1,barrier,gate,18,line
1,barrier,guard_rail,16,line
1,barrier,handrail,16,line
1,barrier,hedge,16,line
1,barrier,kerb,16,line
1,barrier,retaining_wall,16,line
1,barrier,wall,16,line
1,barrier,wire_fence,18,line
1,boundary,historic,18,line
1,highway,abandoned,18,highway
1,highway,bridleway,13,highway
1,highway,bus_guideway,12,highway
1,highway,construction,13,highway
1,highway,cycleway,13,highway
1,highway,footway,13,highway
1,highway,living_street,13,highway
1,highway,motorway,6,highway
1,highway,motorway_link,9,highway
1,highway,path,13,highway
1,highway,pedestrian,13,highway
1,highway,platform,16,highway
1,highway,primary,8,highway
1,highway,primary_link,8,highway
1,highway,proposed,18,highway
1,highway,raceway,12,highway
1,highway,residential,12,highway
1,highway,road,10,highway
1,highway,runway,15,highway
1,highway,secondary,9,highway
1,highway,secondary_link,10,highway
1,highway,service,13,highway
1,highway,steps,13,highway
1,highway,taxiway,15,highway
1,highway,tertiary,10,highway
1,highway,tertiary_link,10,highway
1,highway,track,13,highway
1,highway,trunk,6,highway
1,highway,trunk_link,9,highway
1,highway,unclassified,12,highway
1,historic,citywalls,14,line
1,historic,retaining_wall,18,line
1,historic,wall,18,line
1,man_made,breakwater,12,line
1,man_made,cutline,14,line
1,man_made,embankment,15,line
1,man_made,groyne,12,line
1,man_made,pier,12,line
1,natural,cliff,12,line
1,natural,tree,16,line
1,natural,tree_row,16,line
1,power,cable,18,line
1,power,line,14,line
1,power,minor_line,16,line
1,railway,abandoned,18,highway
1,railway,construction,12,highway
1,railway,dismantled,18,highway
1,railway,disused,15,highway
1,railway,funicular,9,highway
1,railway,light_rail,9,highway
1,railway,miniature,15,highway
1,railway,monorail,14,highway
1,railway,narrow_gauge,9,highway
1,railway,platform,16,highway
1,railway,preserved,12,highway
1,railway,rail,8,highway
1,railway,subway,12,highway
1,railway,tram,12,highway
1,railway,turntable,16,highway
1,route,ferry,8,line
1,waterway,canal,12,line
1,waterway,dam,12,line
1,waterway,derelict_canal,12,line
1,waterway,ditch,12,line
1,waterway,drain,12,line
1,waterway,lock_gate,12,line
1,waterway,river,8,line
1,waterway,stream,12,line
1,waterway,wadi,12,line
1,waterway,weir,12,line
2,addr:housename,*,17,polygon
2,addr:housenumber,*,17,polygon
2,admin_level,10,13,boundary
2,admin_level,1,2,boundary
2,admin_level,2,3,boundary
2,admin_level,3,4,boundary
2,admin_level,4,4,boundary
2,admin_level,5,11,boundary
2,admin_level,6,11,boundary
2,admin_level,7,12,boundary
2,admin_level,8,12,boundary
2,admin_level,9,13,boundary
2,aerialway,station,15,polygon
2,aeroway,aerodrome,10,polygon
2,aeroway,apron,10,polygon
2,aeroway,gate,17,polygon
2,aeroway,helipad,16,polygon
2,aeroway,runway,14,polygon
2,aeroway,taxiway,14,polygon
2,aeroway,terminal,15,polygon
2,amenity,atm,17,polygon
2,amenity,bank,17,polygon
2,amenity,bar,17,polygon
2,amenity,bench,19,polygon
2,amenity,bicycle_parking,10,polygon
2,amenity,bicycle_rental,17,polygon
2,amenity,biergarten,17,polygon
2,amenity,bus_station,16,polygon
2,amenity,cafe,17,polygon
2,amenity,car_rental,17,polygon
2,amenity,car_wash,17,polygon
2,amenity,cinema,16,polygon
2,amenity,clinic,16,polygon
2,amenity,college,10,polygon
2,amenity,community_centre,17,polygon
2,amenity,courthouse,16,polygon
2,amenity,dentist,17,polygon
2,amenity,doctors,17,polygon
2,amenity,drinking_water,17,polygon
2,amenity,embassy,17,polygon
2,amenity,emergency_phone,17,polygon
2,amenity,fast_food,17,polygon
2,amenity,ferry_terminal,10,polygon
2,amenity,fire_station,16,polygon
2,amenity,food_court,17,polygon
2,amenity,fountain,17,polygon
2,amenity,fuel,17,polygon
2,amenity,grave_yard,10,polygon
2,amenity,hospital,10,polygon
2,amenity,hunting_stand,16,polygon
2,amenity,ice_cream,17,polygon
2,amenity,kindergarten,10,polygon
2,amenity,library,16,polygon
2,amenity,marketplace,8,polygon
2,amenity,motorcycle_parking,10,polygon
2,amenity,nightclub,17,polygon
2,amenity,parking,10,polygon
2,amenity,parking_space,18,polygon
2,amenity,pharmacy,17,polygon
2,amenity,place_of_worship,12,polygon
2,amenity,police,16,polygon
2,amenity,post_box,17,polygon
2,amenity,post_office,17,polygon
2,amenity,prison,10,polygon
2,amenity,pub,17,polygon
2,amenity,recycling,17,polygon
2,amenity,restaurant,17,polygon
2,amenity,school,10,polygon
2,amenity,shelter,16,polygon
2,amenity,social_facility,17,polygon
2,amenity,swimming_pool,18,polygon
2,amenity,taxi,17,polygon
2,amenity,telephone,17,polygon
2,amenity,theatre,16,polygon
2,amenity,toilets,17,polygon
2,amenity,townhall,16,polygon
2,amenity,university,10,polygon
2,amenity,veterinary,17,polygon
2,amenity,waste_basket,19,polygon
2,barrier,*,16,polygon
2,boundary,national_park,8,polygon;polygon_exterior
2,boundary,protected_area,8,polygon;polygon_exterior
2,boundary,aboriginal_lands,8,polygon;polygon_exterior
2,building,*,12,building
2,highway,bus_stop,16,polygon
2,highway,cycleway,14,polygon
2,highway,elevator,18,polygon
2,highway,footway,14,polygon
2,highway,ford,16,polygon
2,highway,living_street,14,polygon
2,highway,mini_roundabout,16,polygon
2,highway,path,14,polygon
2,highway,pedestrian,14,polygon
2,highway,platform,16,polygon
2,highway,residential,14,polygon
2,highway,rest_area,10,polygon
2,highway,service,14,polygon
2,highway,services,10,polygon
2,highway,track,14,polygon
2,highway,traffic_signals,17,polygon
2,highway,unclassified,14,polygon
2,historic,archaeological_site,16,polygon
2,historic,memorial,17,polygon
2,historic,monument,16,polygon
2,historic,wayside_cross,16,polygon
2,int_wetland,bog,14,polygon
2,int_wetland,fen,14,polygon
2,int_wetland,mangrove,14,polygon
2,int_wetland,marsh,14,polygon
2,int_wetland,None,10,polygon
2,int_wetland,reedbed,14,polygon
2,int_wetland,saltmarsh,14,polygon
2,int_wetland,string_bog,14,polygon
2,int_wetland,swamp,14,polygon
2,int_wetland,wet_meadow,14,polygon
2,landuse,allotments,10,polygon
2,landuse,basin,0,polygon
2,landuse,brownfield,10,polygon
2,landuse,cemetery,10,polygon
2,landuse,commercial,8,polygon
2,landuse,conservation,18,polygon
2,landuse,construction,10,polygon
2,landuse,farm,10,polygon
2,landuse,farmland,5,polygon
2,landuse,farmyard,10,polygon
2,landuse,flowerbed,18,polygon
2,landuse,forest,5,polygon
2,landuse,garages,12,polygon
2,landuse,grass,10,polygon
2,landuse,greenhouse_horticulture,5,polygon
2,landuse,industrial,8,polygon
2,landuse,landfill,10,polygon
2,landuse,meadow,5,polygon
2,landuse,military,7,polygon
2,landuse,orchard,5,polygon
2,landuse,quarry,10,polygon
2,landuse,railway,10,polygon
2,landuse,recreation_ground,10,polygon
2,landuse,reservoir,0,polygon
2,landuse,residential,8,polygon
2,landuse,retail,8,polygon
2,landuse,traffic_island,18,polygon
2,landuse,village_green,10,polygon
2,landuse,vineyard,5,polygon
2,leisure,common,10,polygon
2,leisure,garden,10,polygon
2,leisure,golf_course,10,polygon
2,leisure,green,18,polygon
2,leisure,marina,14,polygon
2,leisure,miniature_golf,15,polygon
2,leisure,nature_reserve,7,polygon
2,leisure,park,10,polygon
2,leisure,picnic_table,17,polygon
2,leisure,pitch,10,polygon
2,leisure,playground,12,polygon
2,leisure,recreation_ground,10,polygon
2,leisure,slipway,17,polygon
2,leisure,sports_centre,10,polygon
2,leisure,stadium,10,polygon
2,leisure,swimming_pool,14,polygon
2,leisure,track,10,polygon
2,leisure,water_park,14,polygon
2,man_made,breakwater,12,polygon
2,man_made,bridge,12,polygon
2,man_made,cross,16,polygon
2,man_made,gasometer,18,polygon
2,man_made,groyne,12,polygon
2,man_made,lighthouse,15,polygon
2,man_made,mast,17,polygon
2,man_made,pier,12,polygon
2,man_made,reservoir_covered,18,polygon
2,man_made,storage_tank,18,polygon
2,man_made,wastewater_plant,5,polygon
2,man_made,water_works,5,polygon
2,man_made,water_tank,18,polygon
2,man_made,water_tower,17,polygon
2,man_made,windmill,16,polygon
2,military,bunker,18,polygon
2,military,danger_area,9,polygon;polygon_exterior
2,natural,bare_rock,5,polygon
2,natural,bay,0,polygon
2,natural,beach,5,polygon
2,natural,cave_entrance,15,polygon
2,natural,grassland,5,polygon
2,natural,green,18,polygon
2,natural,heath,5,polygon
2,natural,marsh,10,polygon
2,natural,mud,9,polygon
2,natural,peak,11,polygon
2,natural,reef,10,polygon
2,natural,saddle,15,polygon
2,natural,sand,5,polygon
2,natural,scree,5,polygon
2,natural,scrub,5,polygon
2,natural,shingle,5,polygon
2,natural,shoal,5,polygon
2,natural,spring,14,polygon
2,natural,strait,0,polygon
2,natural,tree,17,polygon
2,natural,volcano,11,polygon
2,natural,water,0,polygon
2,natural,wetland,10,polygon
2,natural,wood,5,polygon
2,place,island,4,polygon
2,place,islet,14,polygon
2,power,generator,10,polygon
2,power,plant,10,polygon
2,power,station,10,polygon
2,power,sub_station,12,polygon
2,power,substation,12,polygon
2,railway,halt,15,polygon
2,railway,level_crossing,14,polygon
2,railway,platform,16,polygon
2,railway,station,10,polygon
2,railway,subway_entrance,18,polygon
2,railway,tram_stop,16,polygon
2,shop,*,17,polygon
2,shop,department_store,16,polygon
2,shop,mall,10,polygon
2,shop,supermarket,16,polygon
2,tourism,alpine_hut,12,polygon
2,tourism,attraction,10,polygon
2,tourism,camp_site,10,polygon
2,tourism,caravan_site,10,polygon
2,tourism,chalet,17,polygon
2,tourism,guest_house,17,polygon
2,tourism,hostel,17,polygon
2,tourism,hotel,17,polygon
2,tourism,information,17,polygon
2,tourism,motel,17,polygon
2,tourism,museum,16,polygon
2,tourism,picnic_site,10,polygon
2,tourism,theme_park,10,polygon;polygon_exterior
2,tourism,viewpoint,16,polygon
2,tourism,zoo,10,polygon;polygon_exterior
2,waterway,canal,9,polygon
2,waterway,dam,12,polygon
2,waterway,dock,0,polygon
2,waterway,riverbank,0,polygon
2,waterway,weir,15,polygon
2,wetland,bog,5,polygon
2,wetland,fen,5,polygon
2,wetland,marsh,5,polygon
2,wetland,mud,5,polygon
2,wetland,string_bog,5,polygon
2,wetland,swamp,5,polygon
2,wetland,tidalflat,5,polygon
2,wetland,wet_meadow,5,polygon
"#;
