[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_6"] }

clap="*"
osmquadtree = { git = "https://github.com/jharris2268/osmquadtree-rust.git", branch = "main" }
