[package]
name = "osmquadtree-utils"
version = "0.1.0"
authors = ["James Harris <jimbo.harris@gmail.com>"]
edition = "2021"


[workspace]

[dependencies]
clap="2"
num_cpus = "*"
dialoguer = "*"
sysinfo = "*"
console = "*"



osmquadtree = { path = "../" }


